/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef kibitz_TYPES_H
#define kibitz_TYPES_H

#include <thrift/Thrift.h>
#include <thrift/TApplicationException.h>
#include <thrift/protocol/TProtocol.h>
#include <thrift/transport/TTransport.h>

#include <thrift/cxxfunctional.h>


namespace kibitz {


class Item {
 public:

  static const char* ascii_fingerprint; // = "A0AEEAA2093863EE07C8E9D6E50ADE59";
  static const uint8_t binary_fingerprint[16]; // = {0xA0,0xAE,0xEA,0xA2,0x09,0x38,0x63,0xEE,0x07,0xC8,0xE9,0xD6,0xE5,0x0A,0xDE,0x59};

  Item() : kibitz_generated_id(0) {
  }

  virtual ~Item() throw() {}

  std::map<std::string, std::string>  attributes;
  int64_t kibitz_generated_id;

  void __set_attributes(const std::map<std::string, std::string> & val) {
    attributes = val;
  }

  void __set_kibitz_generated_id(const int64_t val) {
    kibitz_generated_id = val;
  }

  bool operator == (const Item & rhs) const
  {
    if (!(attributes == rhs.attributes))
      return false;
    if (!(kibitz_generated_id == rhs.kibitz_generated_id))
      return false;
    return true;
  }
  bool operator != (const Item &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Item & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

void swap(Item &a, Item &b);

typedef struct _Recommender__isset {
  _Recommender__isset() : video(false), itemTypes(false), displayItems(false), ratingsColumn(false), primaryKey(false) {}
  bool video;
  bool itemTypes;
  bool displayItems;
  bool ratingsColumn;
  bool primaryKey;
} _Recommender__isset;

class Recommender {
 public:

  static const char* ascii_fingerprint; // = "3F18D3B132EB5B730FF079FBDEE92FD0";
  static const uint8_t binary_fingerprint[16]; // = {0x3F,0x18,0xD3,0xB1,0x32,0xEB,0x5B,0x73,0x0F,0xF0,0x79,0xFB,0xDE,0xE9,0x2F,0xD0};

  Recommender() : username(), recommenderName(), clientKey(), homepage(), repoName(), title(), description(), image(), video(), numRecs(0), maxRatingVal(0), ratingsColumn(), primaryKey() {
  }

  virtual ~Recommender() throw() {}

  std::string username;
  std::string recommenderName;
  std::string clientKey;
  std::string homepage;
  std::string repoName;
  std::string title;
  std::string description;
  std::string image;
  std::string video;
  std::map<std::string, std::string>  itemTypes;
  std::vector<std::string>  displayItems;
  int64_t numRecs;
  int64_t maxRatingVal;
  std::string ratingsColumn;
  std::string primaryKey;

  _Recommender__isset __isset;

  void __set_username(const std::string& val) {
    username = val;
  }

  void __set_recommenderName(const std::string& val) {
    recommenderName = val;
  }

  void __set_clientKey(const std::string& val) {
    clientKey = val;
  }

  void __set_homepage(const std::string& val) {
    homepage = val;
  }

  void __set_repoName(const std::string& val) {
    repoName = val;
  }

  void __set_title(const std::string& val) {
    title = val;
  }

  void __set_description(const std::string& val) {
    description = val;
  }

  void __set_image(const std::string& val) {
    image = val;
  }

  void __set_video(const std::string& val) {
    video = val;
  }

  void __set_itemTypes(const std::map<std::string, std::string> & val) {
    itemTypes = val;
  }

  void __set_displayItems(const std::vector<std::string> & val) {
    displayItems = val;
  }

  void __set_numRecs(const int64_t val) {
    numRecs = val;
  }

  void __set_maxRatingVal(const int64_t val) {
    maxRatingVal = val;
  }

  void __set_ratingsColumn(const std::string& val) {
    ratingsColumn = val;
  }

  void __set_primaryKey(const std::string& val) {
    primaryKey = val;
  }

  bool operator == (const Recommender & rhs) const
  {
    if (!(username == rhs.username))
      return false;
    if (!(recommenderName == rhs.recommenderName))
      return false;
    if (!(clientKey == rhs.clientKey))
      return false;
    if (!(homepage == rhs.homepage))
      return false;
    if (!(repoName == rhs.repoName))
      return false;
    if (!(title == rhs.title))
      return false;
    if (!(description == rhs.description))
      return false;
    if (!(image == rhs.image))
      return false;
    if (!(video == rhs.video))
      return false;
    if (!(itemTypes == rhs.itemTypes))
      return false;
    if (!(displayItems == rhs.displayItems))
      return false;
    if (!(numRecs == rhs.numRecs))
      return false;
    if (!(maxRatingVal == rhs.maxRatingVal))
      return false;
    if (!(ratingsColumn == rhs.ratingsColumn))
      return false;
    if (!(primaryKey == rhs.primaryKey))
      return false;
    return true;
  }
  bool operator != (const Recommender &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Recommender & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

void swap(Recommender &a, Recommender &b);

} // namespace

#endif
