/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef kibitz_CONSTANTS_H
#define kibitz_CONSTANTS_H

#include "kibitz_types.h"

namespace kibitz {

class kibitzConstants {
 public:
  kibitzConstants();

};

extern const kibitzConstants g_kibitz_constants;

} // namespace

#endif
