/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "kibitz_types.h"

#include <algorithm>
#include <ostream>

#include <thrift/TToString.h>

namespace kibitz {


Item::~Item() throw() {
}


void Item::__set_attributes(const std::map<std::string, std::string> & val) {
  this->attributes = val;
}

void Item::__set_kibitz_generated_id(const int64_t val) {
  this->kibitz_generated_id = val;
}

void Item::__set_confidence(const int32_t val) {
  this->confidence = val;
}

void Item::__set_predictedPreferences(const double val) {
  this->predictedPreferences = val;
}

const char* Item::ascii_fingerprint = "235731DDD465749C937990D982C869C8";
const uint8_t Item::binary_fingerprint[16] = {0x23,0x57,0x31,0xDD,0xD4,0x65,0x74,0x9C,0x93,0x79,0x90,0xD9,0x82,0xC8,0x69,0xC8};

uint32_t Item::read(::apache::thrift::protocol::TProtocol* iprot) {

  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;

  bool isset_attributes = false;
  bool isset_kibitz_generated_id = false;
  bool isset_confidence = false;
  bool isset_predictedPreferences = false;

  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_MAP) {
          {
            this->attributes.clear();
            uint32_t _size0;
            ::apache::thrift::protocol::TType _ktype1;
            ::apache::thrift::protocol::TType _vtype2;
            xfer += iprot->readMapBegin(_ktype1, _vtype2, _size0);
            uint32_t _i4;
            for (_i4 = 0; _i4 < _size0; ++_i4)
            {
              std::string _key5;
              xfer += iprot->readString(_key5);
              std::string& _val6 = this->attributes[_key5];
              xfer += iprot->readString(_val6);
            }
            xfer += iprot->readMapEnd();
          }
          isset_attributes = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 2:
        if (ftype == ::apache::thrift::protocol::T_I64) {
          xfer += iprot->readI64(this->kibitz_generated_id);
          isset_kibitz_generated_id = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 3:
        if (ftype == ::apache::thrift::protocol::T_I32) {
          xfer += iprot->readI32(this->confidence);
          isset_confidence = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 4:
        if (ftype == ::apache::thrift::protocol::T_DOUBLE) {
          xfer += iprot->readDouble(this->predictedPreferences);
          isset_predictedPreferences = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  if (!isset_attributes)
    throw TProtocolException(TProtocolException::INVALID_DATA);
  if (!isset_kibitz_generated_id)
    throw TProtocolException(TProtocolException::INVALID_DATA);
  if (!isset_confidence)
    throw TProtocolException(TProtocolException::INVALID_DATA);
  if (!isset_predictedPreferences)
    throw TProtocolException(TProtocolException::INVALID_DATA);
  return xfer;
}

uint32_t Item::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  oprot->incrementRecursionDepth();
  xfer += oprot->writeStructBegin("Item");

  xfer += oprot->writeFieldBegin("attributes", ::apache::thrift::protocol::T_MAP, 1);
  {
    xfer += oprot->writeMapBegin(::apache::thrift::protocol::T_STRING, ::apache::thrift::protocol::T_STRING, static_cast<uint32_t>(this->attributes.size()));
    std::map<std::string, std::string> ::const_iterator _iter7;
    for (_iter7 = this->attributes.begin(); _iter7 != this->attributes.end(); ++_iter7)
    {
      xfer += oprot->writeString(_iter7->first);
      xfer += oprot->writeString(_iter7->second);
    }
    xfer += oprot->writeMapEnd();
  }
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("kibitz_generated_id", ::apache::thrift::protocol::T_I64, 2);
  xfer += oprot->writeI64(this->kibitz_generated_id);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("confidence", ::apache::thrift::protocol::T_I32, 3);
  xfer += oprot->writeI32(this->confidence);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("predictedPreferences", ::apache::thrift::protocol::T_DOUBLE, 4);
  xfer += oprot->writeDouble(this->predictedPreferences);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  oprot->decrementRecursionDepth();
  return xfer;
}

void swap(Item &a, Item &b) {
  using ::std::swap;
  swap(a.attributes, b.attributes);
  swap(a.kibitz_generated_id, b.kibitz_generated_id);
  swap(a.confidence, b.confidence);
  swap(a.predictedPreferences, b.predictedPreferences);
}

Item::Item(const Item& other8) {
  attributes = other8.attributes;
  kibitz_generated_id = other8.kibitz_generated_id;
  confidence = other8.confidence;
  predictedPreferences = other8.predictedPreferences;
}
Item& Item::operator=(const Item& other9) {
  attributes = other9.attributes;
  kibitz_generated_id = other9.kibitz_generated_id;
  confidence = other9.confidence;
  predictedPreferences = other9.predictedPreferences;
  return *this;
}
std::ostream& operator<<(std::ostream& out, const Item& obj) {
  using apache::thrift::to_string;
  out << "Item(";
  out << "attributes=" << to_string(obj.attributes);
  out << ", " << "kibitz_generated_id=" << to_string(obj.kibitz_generated_id);
  out << ", " << "confidence=" << to_string(obj.confidence);
  out << ", " << "predictedPreferences=" << to_string(obj.predictedPreferences);
  out << ")";
  return out;
}


Recommender::~Recommender() throw() {
}


void Recommender::__set_username(const std::string& val) {
  this->username = val;
}

void Recommender::__set_recommenderName(const std::string& val) {
  this->recommenderName = val;
}

void Recommender::__set_clientKey(const std::string& val) {
  this->clientKey = val;
}

void Recommender::__set_homepage(const std::string& val) {
  this->homepage = val;
}

void Recommender::__set_repoName(const std::string& val) {
  this->repoName = val;
}

void Recommender::__set_title(const std::string& val) {
  this->title = val;
}

void Recommender::__set_description(const std::string& val) {
  this->description = val;
}

void Recommender::__set_image(const std::string& val) {
  this->image = val;
}

void Recommender::__set_video(const std::string& val) {
  this->video = val;
}

void Recommender::__set_itemTypes(const std::map<std::string, std::string> & val) {
  this->itemTypes = val;
}

void Recommender::__set_displayItems(const std::vector<std::string> & val) {
  this->displayItems = val;
}

void Recommender::__set_numRecs(const int64_t val) {
  this->numRecs = val;
}

void Recommender::__set_maxRatingVal(const int64_t val) {
  this->maxRatingVal = val;
}

void Recommender::__set_ratingsColumn(const std::string& val) {
  this->ratingsColumn = val;
}

void Recommender::__set_primaryKey(const std::string& val) {
  this->primaryKey = val;
}

const char* Recommender::ascii_fingerprint = "3F18D3B132EB5B730FF079FBDEE92FD0";
const uint8_t Recommender::binary_fingerprint[16] = {0x3F,0x18,0xD3,0xB1,0x32,0xEB,0x5B,0x73,0x0F,0xF0,0x79,0xFB,0xDE,0xE9,0x2F,0xD0};

uint32_t Recommender::read(::apache::thrift::protocol::TProtocol* iprot) {

  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;

  bool isset_username = false;
  bool isset_recommenderName = false;
  bool isset_clientKey = false;
  bool isset_homepage = false;
  bool isset_repoName = false;
  bool isset_title = false;
  bool isset_description = false;
  bool isset_image = false;
  bool isset_numRecs = false;
  bool isset_maxRatingVal = false;

  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->username);
          isset_username = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 2:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->recommenderName);
          isset_recommenderName = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 3:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->clientKey);
          isset_clientKey = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 4:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->homepage);
          isset_homepage = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 5:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->repoName);
          isset_repoName = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 6:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->title);
          isset_title = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 7:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->description);
          isset_description = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 8:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->image);
          isset_image = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 9:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->video);
          this->__isset.video = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 10:
        if (ftype == ::apache::thrift::protocol::T_MAP) {
          {
            this->itemTypes.clear();
            uint32_t _size10;
            ::apache::thrift::protocol::TType _ktype11;
            ::apache::thrift::protocol::TType _vtype12;
            xfer += iprot->readMapBegin(_ktype11, _vtype12, _size10);
            uint32_t _i14;
            for (_i14 = 0; _i14 < _size10; ++_i14)
            {
              std::string _key15;
              xfer += iprot->readString(_key15);
              std::string& _val16 = this->itemTypes[_key15];
              xfer += iprot->readString(_val16);
            }
            xfer += iprot->readMapEnd();
          }
          this->__isset.itemTypes = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 11:
        if (ftype == ::apache::thrift::protocol::T_LIST) {
          {
            this->displayItems.clear();
            uint32_t _size17;
            ::apache::thrift::protocol::TType _etype20;
            xfer += iprot->readListBegin(_etype20, _size17);
            this->displayItems.resize(_size17);
            uint32_t _i21;
            for (_i21 = 0; _i21 < _size17; ++_i21)
            {
              xfer += iprot->readString(this->displayItems[_i21]);
            }
            xfer += iprot->readListEnd();
          }
          this->__isset.displayItems = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 12:
        if (ftype == ::apache::thrift::protocol::T_I64) {
          xfer += iprot->readI64(this->numRecs);
          isset_numRecs = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 13:
        if (ftype == ::apache::thrift::protocol::T_I64) {
          xfer += iprot->readI64(this->maxRatingVal);
          isset_maxRatingVal = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 14:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->ratingsColumn);
          this->__isset.ratingsColumn = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 15:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->primaryKey);
          this->__isset.primaryKey = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  if (!isset_username)
    throw TProtocolException(TProtocolException::INVALID_DATA);
  if (!isset_recommenderName)
    throw TProtocolException(TProtocolException::INVALID_DATA);
  if (!isset_clientKey)
    throw TProtocolException(TProtocolException::INVALID_DATA);
  if (!isset_homepage)
    throw TProtocolException(TProtocolException::INVALID_DATA);
  if (!isset_repoName)
    throw TProtocolException(TProtocolException::INVALID_DATA);
  if (!isset_title)
    throw TProtocolException(TProtocolException::INVALID_DATA);
  if (!isset_description)
    throw TProtocolException(TProtocolException::INVALID_DATA);
  if (!isset_image)
    throw TProtocolException(TProtocolException::INVALID_DATA);
  if (!isset_numRecs)
    throw TProtocolException(TProtocolException::INVALID_DATA);
  if (!isset_maxRatingVal)
    throw TProtocolException(TProtocolException::INVALID_DATA);
  return xfer;
}

uint32_t Recommender::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  oprot->incrementRecursionDepth();
  xfer += oprot->writeStructBegin("Recommender");

  xfer += oprot->writeFieldBegin("username", ::apache::thrift::protocol::T_STRING, 1);
  xfer += oprot->writeString(this->username);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("recommenderName", ::apache::thrift::protocol::T_STRING, 2);
  xfer += oprot->writeString(this->recommenderName);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("clientKey", ::apache::thrift::protocol::T_STRING, 3);
  xfer += oprot->writeString(this->clientKey);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("homepage", ::apache::thrift::protocol::T_STRING, 4);
  xfer += oprot->writeString(this->homepage);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("repoName", ::apache::thrift::protocol::T_STRING, 5);
  xfer += oprot->writeString(this->repoName);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("title", ::apache::thrift::protocol::T_STRING, 6);
  xfer += oprot->writeString(this->title);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("description", ::apache::thrift::protocol::T_STRING, 7);
  xfer += oprot->writeString(this->description);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("image", ::apache::thrift::protocol::T_STRING, 8);
  xfer += oprot->writeString(this->image);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("video", ::apache::thrift::protocol::T_STRING, 9);
  xfer += oprot->writeString(this->video);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("itemTypes", ::apache::thrift::protocol::T_MAP, 10);
  {
    xfer += oprot->writeMapBegin(::apache::thrift::protocol::T_STRING, ::apache::thrift::protocol::T_STRING, static_cast<uint32_t>(this->itemTypes.size()));
    std::map<std::string, std::string> ::const_iterator _iter22;
    for (_iter22 = this->itemTypes.begin(); _iter22 != this->itemTypes.end(); ++_iter22)
    {
      xfer += oprot->writeString(_iter22->first);
      xfer += oprot->writeString(_iter22->second);
    }
    xfer += oprot->writeMapEnd();
  }
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("displayItems", ::apache::thrift::protocol::T_LIST, 11);
  {
    xfer += oprot->writeListBegin(::apache::thrift::protocol::T_STRING, static_cast<uint32_t>(this->displayItems.size()));
    std::vector<std::string> ::const_iterator _iter23;
    for (_iter23 = this->displayItems.begin(); _iter23 != this->displayItems.end(); ++_iter23)
    {
      xfer += oprot->writeString((*_iter23));
    }
    xfer += oprot->writeListEnd();
  }
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("numRecs", ::apache::thrift::protocol::T_I64, 12);
  xfer += oprot->writeI64(this->numRecs);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("maxRatingVal", ::apache::thrift::protocol::T_I64, 13);
  xfer += oprot->writeI64(this->maxRatingVal);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("ratingsColumn", ::apache::thrift::protocol::T_STRING, 14);
  xfer += oprot->writeString(this->ratingsColumn);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("primaryKey", ::apache::thrift::protocol::T_STRING, 15);
  xfer += oprot->writeString(this->primaryKey);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  oprot->decrementRecursionDepth();
  return xfer;
}

void swap(Recommender &a, Recommender &b) {
  using ::std::swap;
  swap(a.username, b.username);
  swap(a.recommenderName, b.recommenderName);
  swap(a.clientKey, b.clientKey);
  swap(a.homepage, b.homepage);
  swap(a.repoName, b.repoName);
  swap(a.title, b.title);
  swap(a.description, b.description);
  swap(a.image, b.image);
  swap(a.video, b.video);
  swap(a.itemTypes, b.itemTypes);
  swap(a.displayItems, b.displayItems);
  swap(a.numRecs, b.numRecs);
  swap(a.maxRatingVal, b.maxRatingVal);
  swap(a.ratingsColumn, b.ratingsColumn);
  swap(a.primaryKey, b.primaryKey);
  swap(a.__isset, b.__isset);
}

Recommender::Recommender(const Recommender& other24) {
  username = other24.username;
  recommenderName = other24.recommenderName;
  clientKey = other24.clientKey;
  homepage = other24.homepage;
  repoName = other24.repoName;
  title = other24.title;
  description = other24.description;
  image = other24.image;
  video = other24.video;
  itemTypes = other24.itemTypes;
  displayItems = other24.displayItems;
  numRecs = other24.numRecs;
  maxRatingVal = other24.maxRatingVal;
  ratingsColumn = other24.ratingsColumn;
  primaryKey = other24.primaryKey;
  __isset = other24.__isset;
}
Recommender& Recommender::operator=(const Recommender& other25) {
  username = other25.username;
  recommenderName = other25.recommenderName;
  clientKey = other25.clientKey;
  homepage = other25.homepage;
  repoName = other25.repoName;
  title = other25.title;
  description = other25.description;
  image = other25.image;
  video = other25.video;
  itemTypes = other25.itemTypes;
  displayItems = other25.displayItems;
  numRecs = other25.numRecs;
  maxRatingVal = other25.maxRatingVal;
  ratingsColumn = other25.ratingsColumn;
  primaryKey = other25.primaryKey;
  __isset = other25.__isset;
  return *this;
}
std::ostream& operator<<(std::ostream& out, const Recommender& obj) {
  using apache::thrift::to_string;
  out << "Recommender(";
  out << "username=" << to_string(obj.username);
  out << ", " << "recommenderName=" << to_string(obj.recommenderName);
  out << ", " << "clientKey=" << to_string(obj.clientKey);
  out << ", " << "homepage=" << to_string(obj.homepage);
  out << ", " << "repoName=" << to_string(obj.repoName);
  out << ", " << "title=" << to_string(obj.title);
  out << ", " << "description=" << to_string(obj.description);
  out << ", " << "image=" << to_string(obj.image);
  out << ", " << "video=" << to_string(obj.video);
  out << ", " << "itemTypes=" << to_string(obj.itemTypes);
  out << ", " << "displayItems=" << to_string(obj.displayItems);
  out << ", " << "numRecs=" << to_string(obj.numRecs);
  out << ", " << "maxRatingVal=" << to_string(obj.maxRatingVal);
  out << ", " << "ratingsColumn=" << to_string(obj.ratingsColumn);
  out << ", " << "primaryKey=" << to_string(obj.primaryKey);
  out << ")";
  return out;
}

} // namespace
