/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "kibitz_constants.h"

namespace kibitz {

const kibitzConstants g_kibitz_constants;

kibitzConstants::kibitzConstants() {
}

} // namespace

