(*
 Autogenerated by Thrift Compiler (0.9.2)

 DO NOT EDIT UNLESS YOU ARE SURE YOU KNOW WHAT YOU ARE DOING
*)

open Thrift
open Kibitz_types

class virtual iface :
object
  method virtual createNewIndividualServer : string option -> unit
  method virtual terminateSession : string option -> unit
  method virtual makeRecommendation : string option -> Int64.t option -> Int64.t option -> bool option -> string list option -> item list
  method virtual makeItemBasedRecommendations : string option -> Int64.t option -> Int64.t option -> string list option -> item list
  method virtual getPageItems : string option -> Int64.t option -> Int64.t option -> string list option -> item list
  method virtual getItemCount : string option -> Int64.t
  method virtual recordRatings : string option -> Int64.t option -> Int64.t option -> Int64.t option -> unit
  method virtual deleteRatings : string option -> Int64.t option -> Int64.t option -> unit
  method virtual createNewUser : string option -> string option -> bool option -> string
  method virtual checkUsername : string option -> string option -> bool option -> bool
  method virtual checkLogin : string option -> string option -> string option -> bool option -> bool
  method virtual retrieveUserId : string option -> string option -> Int64.t
  method virtual createNewRecommender : string option -> string option -> string option -> string option -> string option -> string option -> string option -> string option -> string option -> bool
  method virtual getUserRatedItems : string option -> Int64.t option -> string list option -> item list
  method virtual initiateModel : string option -> string option -> string option -> string option -> unit
  method virtual getSearchItems : string option -> string option -> string list option -> string list option -> item list
  method virtual makeOverallRatingBasedOrRandomRecommendation : string option -> string option -> Int64.t option -> string list option -> item list
  method virtual addKibitzUser : string option -> string option -> unit
  method virtual checkCorrectDatahubLogin : string option -> string option -> string option -> string option -> string option -> string option -> string option -> bool
  method virtual checkRatingsColumn : string option -> string option -> string option -> string option -> bool
  method virtual getRecommenders : string option -> recommender list
  method virtual getProfilePicture : string option -> string
  method virtual saveFBProfilePic : string option -> string option -> unit
  method virtual deleteRecommender : string option -> unit
  method virtual updateTemplate : string option -> string option -> string option -> string option -> string option -> string option -> (string,string) Hashtbl.t option -> string list option -> Int64.t option -> Int64.t option -> string option -> string option -> string option -> string option -> string option -> string option -> string option -> unit
  method virtual configurePrefilledUserRatings : string option -> string option -> string option -> string option -> string option -> string option -> string option -> string option -> unit
  method virtual getTables : string option -> string option -> string list
  method virtual getColumns : string option -> string option -> string option -> string list
  method virtual getFirstRepo : string option -> string
  method virtual getNumRepos : string option -> Int64.t
  method virtual getAllRepos : string option -> string list
  method virtual saveCSSData : string option -> string option -> unit
end

class client : Protocol.t -> Protocol.t -> 
object
  method createNewIndividualServer : string -> unit
  method terminateSession : string -> unit
  method makeRecommendation : string -> Int64.t -> Int64.t -> bool -> string list -> item list
  method makeItemBasedRecommendations : string -> Int64.t -> Int64.t -> string list -> item list
  method getPageItems : string -> Int64.t -> Int64.t -> string list -> item list
  method getItemCount : string -> Int64.t
  method recordRatings : string -> Int64.t -> Int64.t -> Int64.t -> unit
  method deleteRatings : string -> Int64.t -> Int64.t -> unit
  method createNewUser : string -> string -> bool -> string
  method checkUsername : string -> string -> bool -> bool
  method checkLogin : string -> string -> string -> bool -> bool
  method retrieveUserId : string -> string -> Int64.t
  method createNewRecommender : string -> string -> string -> string -> string -> string -> string -> string -> string -> bool
  method getUserRatedItems : string -> Int64.t -> string list -> item list
  method initiateModel : string -> string -> string -> string -> unit
  method getSearchItems : string -> string -> string list -> string list -> item list
  method makeOverallRatingBasedOrRandomRecommendation : string -> string -> Int64.t -> string list -> item list
  method addKibitzUser : string -> string -> unit
  method checkCorrectDatahubLogin : string -> string -> string -> string -> string -> string -> string -> bool
  method checkRatingsColumn : string -> string -> string -> string -> bool
  method getRecommenders : string -> recommender list
  method getProfilePicture : string -> string
  method saveFBProfilePic : string -> string -> unit
  method deleteRecommender : string -> unit
  method updateTemplate : string -> string -> string -> string -> string -> string -> (string,string) Hashtbl.t -> string list -> Int64.t -> Int64.t -> string -> string -> string -> string -> string -> string -> string -> unit
  method configurePrefilledUserRatings : string -> string -> string -> string -> string -> string -> string -> string -> unit
  method getTables : string -> string -> string list
  method getColumns : string -> string -> string -> string list
  method getFirstRepo : string -> string
  method getNumRepos : string -> Int64.t
  method getAllRepos : string -> string list
  method saveCSSData : string -> string -> unit
end

class processor : iface ->
object
  inherit Processor.t

  val processMap : (string, int * Protocol.t * Protocol.t -> unit) Hashtbl.t
  method process : Protocol.t -> Protocol.t -> bool
end

